- name: Set up mac. Install git, setup github, clone private bootstrap repo and initialize it.
  hosts: localhost
  gather_facts: true
  vars_files:
  - default_config.yml

  tasks:
  - name: Add custom homebrew repos
    community.general.homebrew_tap:
      name: [
        heroku/brew
      ]

  - name: Install core packages via brew casks
    community.general.homebrew_cask:
      name: "{{ item }}"
    ignore_errors: true
    loop: "{{ homebrew_casks}}"

  - name: Install brew packages
    homebrew:
      name: "{{ item }}"
      state: present
    loop: "{{ homebrew_packages }}"

  - name: Set chrome as default browser
    shell: defaultbrowser chrome

  - name: Check if github is installed
    shell: gh auth status
    register: gh_status
    ignore_errors: true

  - name: gh_login
    shell: gh auth status || yes | ((gh auth login -h github.com -s  admin:public_key -w -p ssh) 2> /tmp/out)
    async: 300
    poll: 0
    register: gh_login
    when: gh_status is failed

  - name: open browser to device
    shell: open -a "Google Chrome" https://github.com/login/device
    async: 0
    when: gh_status is failed

  - name: gh_login
    shell: sleep 1 && cat /tmp/out
    register: gh
    when: gh_status is failed

  - name: echo output
    debug: var=gh.stdout_lines
    when: gh_status is failed

  - name: Waiting on github login to finish
    async_status:
      jid: "{{ gh_login.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 100
    delay: 5
    when: gh_status is failed

  - name: Copy ssh key to profile
    shell: gh ssh-key add -t "uptick-laptop" --type "authentication" ~/.ssh/id_ed25519.pub

  - name: Clone full bootstrap repo
    git:
      repo: "git@github.com:uptick/bootstrap.git"
      dest: "~/bootstrap"
      clone: true
      accept_hostkey: true
